courses/urls.py
from django.urls import path, include

from . import views

app_name = "courses"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:course_id>/set_grade/', views.set_grade, name='set_grade'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('add_course', views.add_course_view, name='add_course'),
    path('add_course_req/<int:course_id>/', views.add_course, name='add_course_req'),
    path('drop_course', views.drop_course_view, name='drop_course'),
    path('drop_course_req/<int:course_id>/', views.drop_course, name='drop_course_req'),
    path('<int:course_id>/complete_course_req/', views.complete_course_req, name='complete_course_req'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/login', permanent=True)),
	path('courses/', include('courses.urls')),
	path('polls/', include('polls.urls')),
    path('catalog', include('catalog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

courses/models.py
import datetime

from django.db import models
from django.utils import timezone

from django.contrib.auth.models import User

class Course(models.Model):
    course_code = models.CharField(max_length=20)
    course_name = models.CharField(max_length=200)

    def __str__(self):
        return self.course_code + ' ' + self.course_name

    def validate_weight(self):
        weight = 0.0
        assessments = Assessment.objects.filter(course=self)
        for assessment in assessments:
            weight += float(assessment.weight)
        return (weight == 100.0)

    def getTotalAverage(self, user_id):
        """
        Calculate total accumulated average, including incomplete assessments,
        calculated out of 100%.
        """
        if not Course.validate_weight(self):
            return 0.0
        mark = 0.0
        assessments = Assessment.objects.filter(course=self)
        for asm in assessments:
            grades = Grade.objects.filter(assessment=asm, user_id=user_id)
            weight = asm.weight/asm.components
            for grade in grades:
                mark += float(grade.mark) * float(weight) / 100
        return mark

    def getWeightedAverage(self, user_id):
        """
        Calculate weighted average of all completed assessments
        Assumption: completed assessments have a mark greater than 0
        """
        if not Course.validate_weight(self):
            return 0.0
        mark = 0.0
        availableMark = 0.0
        assessments = Assessment.objects.filter(course=self)
        for asm in assessments:
            grades = Grade.objects.filter(assessment=asm, user_id=user_id)
            weight = asm.weight/asm.components
            for grade in grades:
                if grade.mark > 0:
                    availableMark += float(weight)
                mark += (float(grade.mark)/100) * float(weight)
        if not availableMark: return 0
        return mark/availableMark * 100

class UserCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    is_current = models.BooleanField(default=True)

    def __str__(self):
        return self.user.username + ' is taking ' + self.course.course_name

class Assessment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    components = models.IntegerField(default=1)
    weight = models.DecimalField(decimal_places=2, max_digits=4)

    def __str__(self):
        return (str)(self.components) + ' ' + self.name + ' worth total of '
        + (str)(self.weight) + '%' + " for " + self.course.course_code


class Grade(models.Model):
    user_id = models.IntegerField(default=1)
    assessment = models.ForeignKey(Assessment, on_delete=models.CASCADE)
    mark = models.FloatField(default=0.0)
    component = models.IntegerField(default=1)

    def __str__(self):
        return self.assessment.__str__() + (str)(self.component)
        + " " + (str)(self.mark) + "%"

courses/views.py
# imports
from django.shortcuts import render
from django.utils import timezone

from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic
from decimal import Decimal
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

from.models import Course, Assessment, Grade, UserCourse

@login_required(login_url='/accounts/login/')
def index(request):
    courses = UserCourse.objects.filter(user=request.user)

    context = {
        'course_list' : courses,
    }

    return render(request, 'courses/index.html', context=context)

# generic DetailView for detail.html
class DetailView(generic.DetailView):
    model = Course
    template_name = 'courses/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Course.objects

@login_required(login_url='/accounts/login/')
def set_grade(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    assessments = Assessment.objects.filter(course=course)
    # loop through assessments and update changed grades
    for assessment in assessments:
        for i in range(1, assessment.components+1):
            mark = request.POST[(str)(assessment.id) + "_" + (str)(i)]
            mark = Decimal.from_float((float)(mark))
            a = Assessment.objects.get(pk=assessment.id)
            try:
                g = a.grade_set.get(component=i, user_id=request.user.id)
                g.mark = mark
                g.save()
            except(Grade.DoesNotExist):
                a.grade_set.create(user_id=request.user.id, mark=mark, component=i)
    # go back to course detail page
    return HttpResponseRedirect(reverse('courses:detail', args=(course.id,)))

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

def add_course_view(request):
    # get a list of courses that the user is taking
    cur_courses = UserCourse.objects.filter(user__pk=request.user.id).values('course')
    # exclude the list of courses
    courses = Course.objects.exclude(pk__in=cur_courses)
    
    context = {
        'course_list' : courses,
    }
    return render(request, 'courses/add_course.html', context=context)

@login_required(login_url='/accounts/login/')
def add_course(request, course_id):
    crs = Course.objects.get(pk=course_id)
    newUC = UserCourse(user=request.user, course=crs)
    newUC.save()
    return redirect('/courses/add_course')

def drop_course_view(request):
    # get a list of courses that the user is taking
    cur_courses = UserCourse.objects.filter(user__pk=request.user.id, is_current=True).values('course')
    # exclude the list of courses
    courses = Course.objects.filter(pk__in=cur_courses)
    
    context = {
        'course_list' : courses,
    }
    return render(request, 'courses/drop_course.html', context=context)

@login_required(login_url='/accounts/login/')
def drop_course(request, course_id):
    crs = Course.objects.get(pk=course_id)
    newUC = UserCourse.objects.get(user=request.user, course=crs)
    newUC.delete()
    return redirect('/courses/drop_course')

@login_required(login_url='/accounts/login/')
def complete_course_req(request, course_id):
    crs = Course.objects.get(pk=course_id)
    userCrs = UserCourse.objects.get(user=request.user, course=crs)
    userCrs.is_current = False
    userCrs.save()
    return redirect('/courses/')

polls/views.py
from django.shortcuts import render
from django.utils import timezone

# Create your views here.
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.views import generic

from.models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    # question = get_object_or_404(Question, pk=question_id)
    # return render(request, 'polls/detail.html', {'question': question})
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results',
                                            args=(question.id,)))

courses/templates/courses/add_course.html
<meta charset="utf-8"/>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}">

{% if user.is_authenticated %}
<div id = "auth_nav"> 
    User: {{ user.get_username }}  <a href="{% url 'logout'%}?next={{request.path}}">Logout</a>
</div>
<title>Add courses</title>
<h1>Click on a course to add</h1>

<div>
<ul>
    {% for course in course_list %}
    <li><a href="{% url 'courses:add_course_req' course.id %}">{{ course.course_code }} {{course.course_name}}</a></li>
    {% endfor %}    
</ul>
</div>

<div> 
    <a class="button" href="{% url 'courses:index' %}"> Back to Courses</a>
</div>

{% else %}
<p> You are not authenticated, please
<a href="{% url 'login'%}?next={{request.path}}">Login</a></p>
{% endif %}

courses/templates/courses/detail.html
<meta charset="utf-8"/>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% load static %}
{% load courses_extra %}
<link rel="stylesheet" type="text/css" href="{% static 'courses/detail.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}">

{% if user.is_authenticated %}
<div id = "auth_nav"> 
User: {{ user.get_username }}  <a class="button" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
</div>

<h1>{{ course.course_code }} {{course.course_name}} <a class="button" href="{% url 'courses:complete_course_req' course.id %}">Complete Course</a></h1>
<title>{{ course.course_code }} {{course.course_name}}</title>
<form action="{% url 'courses:set_grade' course.id %}" method="post">
    {% csrf_token %}
    <div class="table">
        <div class="row">
            <div class="cell">Name</div>
            <div class="cell">Weight</div>
            <div class="cell">Grade(%)</div>
        </div>
        {% for assessment in course.assessment_set.all %}
        {% if assessment.components > 1 %}
        {% for i in 1|filter_range:assessment.components %}
        <div class="row">
            <div class="cell">{{assessment.name}} {{i}}</div>
            <div class="cell">{{assessment.weight|div:assessment.components}}</div>
            <div class="cell">
                <input type="text" name="{{assessment.id}}_{{i}}" value="{% getMark assessment.id i user.id %}" required
                    pattern="^(?:\d{1,2}(?:\.\d{1,2})?|100(?:\.0?0)?)" />
            </div>
        </div>
        {% endfor %}
        {% else%}
        <div class="row">
            <div class="cell">{{assessment.name}}</div>
            <div class="cell">{{assessment.weight}}</div>
            <div class="cell">
                <input type="text" name="{{assessment.id}}_1" value="{% getMark assessment.id 1 user.id %}" required
                    pattern="^(?:\d{1,2}(?:\.\d{1,2})?|100(?:\.0?0)?)" />
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    <div class="average">
        <div class="total">Total Average: {{course.id|getTotalAverage:user.id}}%</div>
        <div class="weighted">Weighted Average: {{course.id|getWeightedAverage:user.id}}%</div>
    </div>
    <input class="button" type="submit" value="Save Changes">
    <div> 
        <a class="button" href="{% url 'courses:index' %}"> Back to Courses</a>
    </div>
</form>

{% else %}
<p> You are not authenticated, please
<a href="{% url 'login'%}?next={{request.path}}">Login</a></p>
{% endif %}

courses/templates/courses/drop_course.html
<meta charset="utf-8"/>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}">

{% if user.is_authenticated %}
<div id = "auth_nav"> 
    User: {{ user.get_username }}  <a href="{% url 'logout'%}?next={{request.path}}">Logout</a>
</div>
<title>Drop courses</title>
<h1>Click on a course to drop</h1>

<div>
<ul>
    {% for course in course_list %}
    <li><a href="{% url 'courses:drop_course_req' course.id %}">{{ course.course_code }} {{course.course_name}}</a></li>
    {% endfor %}    
</ul>
</div>

<div> 
    <a class="button" href="{% url 'courses:index' %}"> Back to Courses</a>
</div>

{% else %}
<p> You are not authenticated, please
<a href="{% url 'login'%}?next={{request.path}}">Login</a></p>
{% endif %}

courses/templates/courses/index.html
<meta charset="utf-8"/>
{% load static %}
<title>Course Manager</title>
<link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}">

<h1>Course Manager</h1>

{% if user.is_authenticated %}
<div>
    User: {{ user.get_username }}
    <a class="button" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
</div>

<a class="button" href="{% url 'courses:add_course' %}">Add Course</a>
<a class="button" href="{% url 'courses:drop_course' %}">Drop Course</a>
<h2>Current Courses</h2>

{% if course_list %}
<ul>
    {% for usercourse in course_list %}
        {% if usercourse.is_current %}
        <li><a href="{% url 'courses:detail' usercourse.course.id %}">{{ usercourse.course.course_code }} {{ usercourse.course.course_name}}</a></li>
        {% endif %}
    {% endfor %}
</ul>
{% else %}
<p>No courses are registered.</p>
{% endif %}

<h2>Past Courses</h2>
{% if course_list %}
<ul>
    {% for usercourse in course_list %}
        {% if not usercourse.is_current%}
        <li><a href="{% url 'courses:detail' usercourse.course.id %}">{{ usercourse.course.course_code }} {{ usercourse.course.course_name}}</a></li>
        {% endif%}
    {% endfor %}
</ul>
{% else %}
<p>No courses are taken in the past.</p>
{% endif %}

{% else %}
<p> You are not authenticated, please
<a href="{% url 'login'%}?next={{request.path}}">Login</a></p>
{% endif %}